language: cpp
dist: precise

os:
  - linux

compiler:
  - gcc
  - clang

addons:
  apt:
    sources:
      - debian-sid
    packages:
      - libsfml-dev

before_script:
  - mkdir build
  - cd build
  - cmake ..
script:
  - make
